/*
 _____               _____
|_   _| __ _   _  __|_   _|__ _ __ ___  _ __ ___
  | || '__| | | |/ _ \| |/ _ \ '_ ` _ \| '_ ` _ \
  | || |  | |_| |  __/| |  __/ | | | | | | | | | |
  |_||_|   \__,_|\___||_|\___|_| |_| |_|_| |_| |_|

 _____ __  __       ____                               __ _
|_   _|  \/  |     |  _ \ _ __ __ _  __ _  ___  _ __  / _| |_   _
  | | | |\/| |_____| | | | '__/ _` |/ _` |/ _ \| '_ \| |_| | | | |
  | | | |  | |_____| |_| | | | (_| | (_| | (_) | | | |  _| | |_| |
  |_| |_|  |_|     |____/|_|  \__,_|\__, |\___/|_| |_|_| |_|\__, |
                                    |___/                   |___/

@author TrueTemm
@link   https://github.com/TrueTemm
TM-Dragonfly Project
*/

package v786

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

const (
	SoundEventItemUseOn = iota
	SoundEventHit
	SoundEventStep
	SoundEventFly
	SoundEventJump
	SoundEventBreak
	SoundEventPlace
	SoundEventHeavyStep
	SoundEventGallop
	SoundEventFall
	SoundEventAmbient
	SoundEventAmbientBaby
	SoundEventAmbientInWater
	SoundEventBreathe
	SoundEventDeath
	SoundEventDeathInWater
	SoundEventDeathToZombie
	SoundEventHurt
	SoundEventHurtInWater
	SoundEventMad
	SoundEventBoost
	SoundEventBow
	SoundEventSquishBig
	SoundEventSquishSmall
	SoundEventFallBig
	SoundEventFallSmall
	SoundEventSplash
	SoundEventFizz
	SoundEventFlap
	SoundEventSwim
	SoundEventDrink
	SoundEventEat
	SoundEventTakeoff
	SoundEventShake
	SoundEventPlop
	SoundEventLand
	SoundEventSaddle
	SoundEventArmor
	SoundEventArmorPlace
	SoundEventAddChest
	SoundEventThrow
	SoundEventAttack
	SoundEventAttackNoDamage
	SoundEventAttackStrong
	SoundEventWarn
	SoundEventShear
	SoundEventMilk
	SoundEventThunder
	SoundEventExplode
	SoundEventFire
	SoundEventIgnite
	SoundEventFuse
	SoundEventStare
	SoundEventSpawn
	SoundEventShoot
	SoundEventBreakBlock
	SoundEventLaunch
	SoundEventBlast
	SoundEventLargeBlast
	SoundEventTwinkle
	SoundEventRemedy
	SoundEventUnfect
	SoundEventLevelUp
	SoundEventBowHit
	SoundEventBulletHit
	SoundEventExtinguishFire
	SoundEventItemFizz
	SoundEventChestOpen
	SoundEventChestClosed
	SoundEventShulkerBoxOpen
	SoundEventShulkerBoxClosed
	SoundEventEnderChestOpen
	SoundEventEnderChestClosed
	SoundEventPowerOn
	SoundEventPowerOff
	SoundEventAttach
	SoundEventDetach
	SoundEventDeny
	SoundEventTripod
	SoundEventPop
	SoundEventDropSlot
	SoundEventNote
	SoundEventThorns
	SoundEventPistonIn
	SoundEventPistonOut
	SoundEventPortal
	SoundEventWater
	SoundEventLavaPop
	SoundEventLava
	SoundEventBurp
	SoundEventBucketFillWater
	SoundEventBucketFillLava
	SoundEventBucketEmptyWater
	SoundEventBucketEmptyLava
	SoundEventEquipChain
	SoundEventEquipDiamond
	SoundEventEquipGeneric
	SoundEventEquipGold
	SoundEventEquipIron
	SoundEventEquipLeather
	SoundEventEquipElytra
	SoundEventRecord13
	SoundEventRecordCat
	SoundEventRecordBlocks
	SoundEventRecordChirp
	SoundEventRecordFar
	SoundEventRecordMall
	SoundEventRecordMellohi
	SoundEventRecordStal
	SoundEventRecordStrad
	SoundEventRecordWard
	SoundEventRecord11
	SoundEventRecordWait
	SoundEventRecordNull
	SoundEventFlop
	SoundEventGuardianCurse
	SoundEventMobWarning
	SoundEventMobWarningBaby
	SoundEventTeleport
	SoundEventShulkerOpen
	SoundEventShulkerClose
	SoundEventHaggle
	SoundEventHaggleYes
	SoundEventHaggleNo
	SoundEventHaggleIdle
	SoundEventChorusGrow
	SoundEventChorusDeath
	SoundEventGlass
	SoundEventPotionBrewed
	SoundEventCastSpell
	SoundEventPrepareAttackSpell
	SoundEventPrepareSummon
	SoundEventPrepareWololo
	SoundEventFang
	SoundEventCharge
	SoundEventTakePicture
	SoundEventPlaceLeashKnot
	SoundEventBreakLeashKnot
	SoundEventAmbientGrowl
	SoundEventAmbientWhine
	SoundEventAmbientPant
	SoundEventAmbientPurr
	SoundEventAmbientPurreow
	SoundEventDeathMinVolume
	SoundEventDeathMidVolume
	SoundEventImitateBlaze
	SoundEventImitateCaveSpider
	SoundEventImitateCreeper
	SoundEventImitateElderGuardian
	SoundEventImitateEnderDragon
	SoundEventImitateEnderman
	SoundEventImitateEndermite
	SoundEventImitateEvocationIllager
	SoundEventImitateGhast
	SoundEventImitateHusk
	SoundEventImitateIllusionIllager
	SoundEventImitateMagmaCube
	SoundEventImitatePolarBear
	SoundEventImitateShulker
	SoundEventImitateSilverfish
	SoundEventImitateSkeleton
	SoundEventImitateSlime
	SoundEventImitateSpider
	SoundEventImitateStray
	SoundEventImitateVex
	SoundEventImitateVindicationIllager
	SoundEventImitateWitch
	SoundEventImitateWither
	SoundEventImitateWitherSkeleton
	SoundEventImitateWolf
	SoundEventImitateZombie
	SoundEventImitateZombiePigman
	SoundEventImitateZombieVillager
	SoundEventEnderEyePlaced
	SoundEventEndPortalCreated
	SoundEventAnvilUse
	SoundEventBottleDragonBreath
	SoundEventPortalTravel
	SoundEventTridentHit
	SoundEventTridentReturn
	SoundEventTridentRiptide1
	SoundEventTridentRiptide2
	SoundEventTridentRiptide3
	SoundEventTridentThrow
	SoundEventTridentThunder
	SoundEventTridentHitGround
	SoundEventDefault
	SoundEventFletchingTableUse
	SoundEventElemConstructOpen
	SoundEventIceBombHit
	SoundEventBalloonPop
	SoundEventLtReactionIceBomb
	SoundEventLtReactionBleach
	SoundEventLtReactionElephantToothpaste
	SoundEventLtReactionElephantToothpaste2
	SoundEventLtReactionGlowStick
	SoundEventLtReactionGlowStick2
	SoundEventLtReactionLuminol
	SoundEventLtReactionSalt
	SoundEventLtReactionFertilizer
	SoundEventLtReactionFireball
	SoundEventLtReactionMagnesiumSalt
	SoundEventLtReactionMiscFire
	SoundEventLtReactionFire
	SoundEventLtReactionMiscExplosion
	SoundEventLtReactionMiscMystical
	SoundEventLtReactionMiscMystical2
	SoundEventLtReactionProduct
	SoundEventSparklerUse
	SoundEventGlowStickUse
	SoundEventSparklerActive
	SoundEventConvertToDrowned
	SoundEventBucketFillFish
	SoundEventBucketEmptyFish
	SoundEventBubbleColumnUpwards
	SoundEventBubbleColumnDownwards
	SoundEventBubblePop
	SoundEventBubbleUpInside
	SoundEventBubbleDownInside
	SoundEventHurtBaby
	SoundEventDeathBaby
	SoundEventStepBaby
	SoundEventSpawnBaby
	SoundEventBorn
	SoundEventTurtleEggBreak
	SoundEventTurtleEggCrack
	SoundEventTurtleEggHatched
	SoundEventLayEgg
	SoundEventTurtleEggAttacked
	SoundEventBeaconActivate
	SoundEventBeaconAmbient
	SoundEventBeaconDeactivate
	SoundEventBeaconPower
	SoundEventConduitActivate
	SoundEventConduitAmbient
	SoundEventConduitAttack
	SoundEventConduitDeactivate
	SoundEventConduitShort
	SoundEventSwoop
	SoundEventBambooSaplingPlace
	SoundEventPreSneeze
	SoundEventSneeze
	SoundEventAmbientTame
	SoundEventScared
	SoundEventScaffoldingClimb
	SoundEventCrossbowLoadingStart
	SoundEventCrossbowLoadingMiddle
	SoundEventCrossbowLoadingEnd
	SoundEventCrossbowShoot
	SoundEventCrossbowQuickChargeStart
	SoundEventCrossbowQuickChargeMiddle
	SoundEventCrossbowQuickChargeEnd
	SoundEventAmbientAggressive
	SoundEventAmbientWorried
	SoundEventCantBreed
	SoundEventShieldBlock
	SoundEventLecternBookPlace
	SoundEventGrindstoneUse
	SoundEventBell
	SoundEventCampfireCrackle
	SoundEventRoar
	SoundEventStun
	SoundEventSweetBerryBushHurt
	SoundEventSweetBerryBushPick
	SoundEventCartographyTableUse
	SoundEventStonecutterUse
	SoundEventComposterEmpty
	SoundEventComposterFill
	SoundEventComposterFillLayer
	SoundEventComposterReady
	SoundEventBarrelOpen
	SoundEventBarrelClose
	SoundEventRaidHorn
	SoundEventLoomUse
	SoundEventAmbientInRaid
	SoundEventUicartographyTableUse
	SoundEventUistonecutterUse
	SoundEventUiloomUse
	SoundEventSmokerUse
	SoundEventBlastFurnaceUse
	SoundEventSmithingTableUse
	SoundEventScreech
	SoundEventSleep
	SoundEventFurnaceUse
	SoundEventMooshroomConvert
	SoundEventMilkSuspiciously
	SoundEventCelebrate
	SoundEventJumpPrevent
	SoundEventAmbientPollinate
	SoundEventBeehiveDrip
	SoundEventBeehiveEnter
	SoundEventBeehiveExit
	SoundEventBeehiveWork
	SoundEventBeehiveShear
	SoundEventHoneybottleDrink
	SoundEventAmbientCave
	SoundEventRetreat
	SoundEventConvertToZombified
	SoundEventAdmire
	SoundEventStepLava
	SoundEventTempt
	SoundEventPanic
	SoundEventAngry
	SoundEventAmbientMoodWarpedForest
	SoundEventAmbientMoodSoulsandValley
	SoundEventAmbientMoodNetherWastes
	SoundEventAmbientMoodBasaltDeltas
	SoundEventAmbientMoodCrimsonForest
	SoundEventRespawnAnchorCharge
	SoundEventRespawnAnchorDeplete
	SoundEventRespawnAnchorSetSpawn
	SoundEventRespawnAnchorAmbient
	SoundEventSoulEscapeQuiet
	SoundEventSoulEscapeLoud
	SoundEventRecordPigstep
	SoundEventLinkCompassToLodestone
	SoundEventUseSmithingTable
	SoundEventEquipNetherite
	SoundEventAmbientLoopWarpedForest
	SoundEventAmbientLoopSoulsandValley
	SoundEventAmbientLoopNetherWastes
	SoundEventAmbientLoopBasaltDeltas
	SoundEventAmbientLoopCrimsonForest
	SoundEventAmbientAdditionWarpedForest
	SoundEventAmbientAdditionSoulsandValley
	SoundEventAmbientAdditionNetherWastes
	SoundEventAmbientAdditionBasaltDeltas
	SoundEventAmbientAdditionCrimsonForest
	SoundEventSculkSensorPowerOn
	SoundEventSculkSensorPowerOff
	SoundEventBucketFillPowderSnow
	SoundEventBucketEmptyPowderSnow
	SoundEventPointedDripstoneCauldronDripWater
	SoundEventPointedDripstoneCauldronDripLava
	SoundEventPointedDripstoneDripWater
	SoundEventPointedDripstoneDripLava
	SoundEventCaveVinesPickBerries
	SoundEventBigDripleafTiltDown
	SoundEventBigDripleafTiltUp
	SoundEventCopperWaxOn
	SoundEventCopperWaxOff
	SoundEventScrape
	SoundEventPlayerHurtDrown
	SoundEventPlayerHurtOnFire
	SoundEventPlayerHurtFreeze
	SoundEventUseSpyglass
	SoundEventStopUsingSpyglass
	SoundEventAmethystBlockChime
	SoundEventAmbientScreamer
	SoundEventHurtScreamer
	SoundEventDeathScreamer
	SoundEventMilkScreamer
	SoundEventJumpToBlock
	SoundEventPreRam
	SoundEventPreRamScreamer
	SoundEventRamImpact
	SoundEventRamImpactScreamer
	SoundEventSquidInkSquirt
	SoundEventGlowSquidInkSquirt
	SoundEventConvertToStray
	SoundEventCakeAddCandle
	SoundEventExtinguishCandle
	SoundEventAmbientCandle
	SoundEventBlockClick
	SoundEventBlockClickFail
	SoundEventSculkCatalystBloom
	SoundEventSculkShriekerShriek
	SoundEventWardenNearbyClose
	SoundEventWardenNearbyCloser
	SoundEventWardenNearbyClosest
	SoundEventWardenSlightlyAngry
	SoundEventRecordOtherside
	SoundEventTongue
	SoundEventCrackIronGolem
	SoundEventRepairIronGolem
	SoundEventListening
	SoundEventHeartbeat
	SoundEventHornBreak
	_
	SoundEventSculkSpread
	SoundEventSculkCharge
	SoundEventSculkSensorPlace
	SoundEventSculkShriekerPlace
	SoundEventGoatCall0
	SoundEventGoatCall1
	SoundEventGoatCall2
	SoundEventGoatCall3
	SoundEventGoatCall4
	SoundEventGoatCall5
	SoundEventGoatCall6
	SoundEventGoatCall7
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	_
	SoundEventImitateWarden
	SoundEventListeningAngry
	SoundEventItemGiven
	SoundEventItemTaken
	SoundEventDisappeared
	SoundEventReappeared
	SoundEventDrinkMilk
	SoundEventFrogspawnHatched
	SoundEventLaySpawn
	SoundEventFrogspawnBreak
	SoundEventSonicBoom
	SoundEventSonicCharge
	SoundeventItemThrown
	SoundEventRecord5
	SoundEventConvertToFrog
	SoundEventRecordPlaying
	SoundEventEnchantingTableUse
	SoundEventStepSand
	SoundEventDashReady
	SoundEventBundleDropContents
	SoundEventBundleInsert
	SoundEventBundleRemoveOne
	SoundEventPressurePlateClickOff
	SoundEventPressurePlateClickOn
	SoundEventButtonClickOff
	SoundEventButtonClickOn
	SoundEventDoorOpen
	SoundEventDoorClose
	SoundEventTrapdoorOpen
	SoundEventTrapdoorClose
	SoundEventFenceGateOpen
	SoundEventFenceGateClose
	SoundEventInsert
	SoundEventPickup
	SoundEventInsertEnchanted
	SoundEventPickupEnchanted
	SoundEventBrush
	SoundEventBrushCompleted
	SoundEventShatterDecoratedPot
	SoundEventBreakDecoratedPot
	SoundEventSnifferEggCrack
	SoundEventSnifferEggHatched
	SoundEventWaxedSignInteractFail
	SoundEventRecordRelic
	SoundEventBump
	SoundEventPumpkinCarve
	SoundEventConvertHuskToZombie
	SoundEventPigDeath
	SoundEventHoglinZombified
	SoundEventAmbientUnderwaterEnter
	SoundEventAmbientUnderwaterExit
	SoundEventBottleFill
	SoundEventBottleEmpty
	SoundEventCrafterCraft
	SoundEventCrafterFail
	SoundEventDecoratedPotInsert
	SoundEventDecoratedPotInsertFail
	SoundEventCrafterDisableSlot
	SoundEventTrialSpawnerOpenShutter
	SoundEventTrialSpawnerEjectItem
	SoundEventTrialSpawnerDetectPlayer
	SoundEventTrialSpawnerSpawnMob
	SoundEventTrialSpawnerCloseShutter
	SoundEventTrialSpawnerAmbient
	SoundEventCopperBulbTurnOn
	SoundEventCopperBulbTurnOff
	SoundEventAmbientInAir
	SoundEventBreezeWindChargeBurst
	SoundEventImitateBreeze
	SoundEventArmadilloBrush
	SoundEventArmadilloScuteDrop
	SoundEventEquipWolf
	SoundEventUnequipWolf
	SoundEventReflect
	SoundEventVaultOpenShutter
	SoundEventVaultCloseShutter
	SoundEventVaultEjectItem
	SoundEventVaultInsertItem
	SoundEventVaultInsertItemFail
	SoundEventVaultAmbient
	SoundEventVaultActivate
	SoundEventVaultDeactive
	SoundEventHurtReduced
	SoundEventWindChargeBurst
	SoundEventImitateBogged
	SoundEventWolfArmourCrack
	SoundEventWolfArmourBreak
	SoundEventWolfArmourRepair
	SoundEventMaceSmashAir
	SoundEventMaceSmashGround
	SoundEventTrialSpawnerChargeActivate
	SoundEventTrialSpawnerAmbientOminous
	SoundEventOminiousItemSpawnerSpawnItem
	SoundEventOminousBottleEndUse
	SoundEventMaceHeavySmashGround
	SoundEventOminousItemSpawnerSpawnItemBegin
	_
	SoundEventApplyEffectBadOmen
	SoundEventApplyEffectRaidOmen
	SoundEventApplyEffectTrialOmen
	SoundEventOminousItemSpawnerAboutToSpawnItem
	SoundEventRecordCreator
	SoundEventRecordCreatorMusicBox
	SoundEventRecordPrecipice
	SoundEventVaultRejectRewardedPlayer
	SoundEventImitateDrowned
	SoundEventBundleInsertFailed
)

type LevelSoundEvent struct {
	SoundType uint32

	Position mgl32.Vec3

	ExtraData int32

	EntityType string

	BabyMob bool

	DisableRelativeVolume bool

	EntityUniqueID int64
}

func (*LevelSoundEvent) ID() uint32 {
	return IDLevelSoundEvent
}

func (pk *LevelSoundEvent) Marshal(io protocol.IO) {
	io.Varuint32(&pk.SoundType)
	io.Vec3(&pk.Position)
	io.Varint32(&pk.ExtraData)
	io.String(&pk.EntityType)
	io.Bool(&pk.BabyMob)
	io.Bool(&pk.DisableRelativeVolume)
	io.Int64(&pk.EntityUniqueID)
}
