/*
 _____               _____
|_   _| __ _   _  __|_   _|__ _ __ ___  _ __ ___
  | || '__| | | |/ _ \| |/ _ \ '_ ` _ \| '_ ` _ \
  | || |  | |_| |  __/| |  __/ | | | | | | | | | |
  |_||_|   \__,_|\___||_|\___|_| |_| |_|_| |_| |_|

 _____ __  __       ____                               __ _
|_   _|  \/  |     |  _ \ _ __ __ _  __ _  ___  _ __  / _| |_   _
  | | | |\/| |_____| | | | '__/ _` |/ _` |/ _ \| '_ \| |_| | | | |
  | | | |  | |_____| |_| | | | (_| | (_| | (_) | | | |  _| | |_| |
  |_| |_|  |_|     |____/|_|  \__,_|\__, |\___/|_| |_|_| |_|\__, |
                                    |___/                   |___/

@author TrueTemm
@link   https://github.com/TrueTemm
TM-Dragonfly Project
*/

package v786

import (
	"github.com/sandertv/gophertunnel/minecraft/protocol/packet"
)

func NewServerPool() packet.Pool {
	serverOriginating := map[uint32]func() packet.Packet{
		IDLogin:                             func() packet.Packet { return &packet.Login{} },
		IDPlayStatus:                        func() packet.Packet { return &packet.PlayStatus{} },
		IDServerToClientHandshake:           func() packet.Packet { return &packet.ServerToClientHandshake{} },
		IDClientToServerHandshake:           func() packet.Packet { return &packet.ClientToServerHandshake{} },
		IDDisconnect:                        func() packet.Packet { return &Disconnect{} },
		IDResourcePacksInfo:                 func() packet.Packet { return &ResourcePacksInfo{} },
		IDResourcePackStack:                 func() packet.Packet { return &ResourcePackStack{} },
		IDResourcePackClientResponse:        func() packet.Packet { return &ResourcePackClientResponse{} },
		IDText:                              func() packet.Packet { return &Text{} },
		IDSetTime:                           func() packet.Packet { return &packet.SetTime{} },
		IDStartGame:                         func() packet.Packet { return &StartGame{} },
		IDAddPlayer:                         func() packet.Packet { return &AddPlayer{} },
		IDAddActor:                          func() packet.Packet { return &AddActor{} },
		IDRemoveActor:                       func() packet.Packet { return &packet.RemoveActor{} },
		IDAddItemActor:                      func() packet.Packet { return &AddItemActor{} },
		IDTakeItemActor:                     func() packet.Packet { return &packet.TakeItemActor{} },
		IDMoveActorAbsolute:                 func() packet.Packet { return &packet.MoveActorAbsolute{} },
		IDMovePlayer:                        func() packet.Packet { return &MovePlayer{} },
		IDPassengerJump:                     func() packet.Packet { return &PassengerJump{} },
		IDUpdateBlock:                       func() packet.Packet { return &UpdateBlock{} },
		IDAddPainting:                       func() packet.Packet { return &packet.AddPainting{} },
		IDTickSync:                          func() packet.Packet { return &TickSync{} },
		IDLevelEvent:                        func() packet.Packet { return &packet.LevelEvent{} },
		IDBlockEvent:                        func() packet.Packet { return &BlockEvent{} },
		IDActorEvent:                        func() packet.Packet { return &ActorEvent{} },
		IDMobEffect:                         func() packet.Packet { return &MobEffect{} },
		IDUpdateAttributes:                  func() packet.Packet { return &packet.UpdateAttributes{} },
		IDInventoryTransaction:              func() packet.Packet { return &InventoryTransaction{} },
		IDMobEquipment:                      func() packet.Packet { return &packet.MobEquipment{} },
		IDMobArmourEquipment:                func() packet.Packet { return &packet.MobArmourEquipment{} },
		IDInteract:                          func() packet.Packet { return &Interact{} },
		IDBlockPickRequest:                  func() packet.Packet { return &packet.BlockPickRequest{} },
		IDActorPickRequest:                  func() packet.Packet { return &packet.ActorPickRequest{} },
		IDPlayerAction:                      func() packet.Packet { return &PlayerAction{} },
		IDHurtArmour:                        func() packet.Packet { return &HurtArmour{} },
		IDSetActorData:                      func() packet.Packet { return &SetActorData{} },
		IDSetActorMotion:                    func() packet.Packet { return &packet.SetActorMotion{} },
		IDSetActorLink:                      func() packet.Packet { return &packet.SetActorLink{} },
		IDSetHealth:                         func() packet.Packet { return &packet.SetHealth{} },
		IDSetSpawnPosition:                  func() packet.Packet { return &SetSpawnPosition{} },
		IDAnimate:                           func() packet.Packet { return &Animate{} },
		IDRespawn:                           func() packet.Packet { return &packet.Respawn{} },
		IDContainerOpen:                     func() packet.Packet { return &ContainerOpen{} },
		IDContainerClose:                    func() packet.Packet { return &ContainerClose{} },
		IDPlayerHotBar:                      func() packet.Packet { return &packet.PlayerHotBar{} },
		IDInventoryContent:                  func() packet.Packet { return &packet.InventoryContent{} },
		IDInventorySlot:                     func() packet.Packet { return &InventorySlot{} },
		IDContainerSetData:                  func() packet.Packet { return &packet.ContainerSetData{} },
		IDCraftingData:                      func() packet.Packet { return &CraftingData{} },
		IDGUIDataPickItem:                   func() packet.Packet { return &packet.GUIDataPickItem{} },
		IDAdventureSettings:                 func() packet.Packet { return &packet.AdventureSettings{} },
		IDBlockActorData:                    func() packet.Packet { return &BlockActorData{} },
		IDPlayerInput:                       func() packet.Packet { return &PlayerInput{} },
		IDLevelChunk:                        func() packet.Packet { return &LevelChunk{} },
		IDSetCommandsEnabled:                func() packet.Packet { return &packet.SetCommandsEnabled{} },
		IDSetDifficulty:                     func() packet.Packet { return &packet.SetDifficulty{} },
		IDChangeDimension:                   func() packet.Packet { return &ChangeDimension{} },
		IDSetPlayerGameType:                 func() packet.Packet { return &packet.SetPlayerGameType{} },
		IDPlayerList:                        func() packet.Packet { return &PlayerList{} },
		IDSimpleEvent:                       func() packet.Packet { return &SimpleEvent{} },
		IDEvent:                             func() packet.Packet { return &Event{} },
		IDSpawnExperienceOrb:                func() packet.Packet { return &packet.SpawnExperienceOrb{} },
		IDClientBoundMapItemData:            func() packet.Packet { return &ClientBoundMapItemData{} },
		IDMapInfoRequest:                    func() packet.Packet { return &packet.MapInfoRequest{} },
		IDRequestChunkRadius:                func() packet.Packet { return &RequestChunkRadius{} },
		IDChunkRadiusUpdated:                func() packet.Packet { return &packet.ChunkRadiusUpdated{} },
		IDGameRulesChanged:                  func() packet.Packet { return &packet.GameRulesChanged{} },
		IDCamera:                            func() packet.Packet { return &packet.Camera{} },
		IDBossEvent:                         func() packet.Packet { return &BossEvent{} },
		IDShowCredits:                       func() packet.Packet { return &packet.ShowCredits{} },
		IDAvailableCommands:                 func() packet.Packet { return &AvailableCommands{} },
		IDCommandRequest:                    func() packet.Packet { return &CommandRequest{} },
		IDCommandBlockUpdate:                func() packet.Packet { return &CommandBlockUpdate{} },
		IDCommandOutput:                     func() packet.Packet { return &CommandOutput{} },
		IDUpdateTrade:                       func() packet.Packet { return &packet.UpdateTrade{} },
		IDUpdateEquip:                       func() packet.Packet { return &packet.UpdateEquip{} },
		IDResourcePackDataInfo:              func() packet.Packet { return &packet.ResourcePackDataInfo{} },
		IDResourcePackChunkData:             func() packet.Packet { return &packet.ResourcePackChunkData{} },
		IDResourcePackChunkRequest:          func() packet.Packet { return &ResourcePackChunkRequest{} },
		IDTransfer:                          func() packet.Packet { return &Transfer{} },
		IDPlaySound:                         func() packet.Packet { return &PlaySound{} },
		IDStopSound:                         func() packet.Packet { return &packet.StopSound{} },
		IDSetTitle:                          func() packet.Packet { return &packet.SetTitle{} },
		IDAddBehaviourTree:                  func() packet.Packet { return &packet.AddBehaviourTree{} },
		IDStructureBlockUpdate:              func() packet.Packet { return &StructureBlockUpdate{} },
		IDShowStoreOffer:                    func() packet.Packet { return &ShowStoreOffer{} },
		IDPurchaseReceipt:                   func() packet.Packet { return &packet.PurchaseReceipt{} },
		IDPlayerSkin:                        func() packet.Packet { return &PlayerSkin{} },
		IDSubClientLogin:                    func() packet.Packet { return &packet.SubClientLogin{} },
		IDAutomationClientConnect:           func() packet.Packet { return &packet.AutomationClientConnect{} },
		IDSetLastHurtBy:                     func() packet.Packet { return &packet.SetLastHurtBy{} },
		IDBookEdit:                          func() packet.Packet { return &BookEdit{} },
		IDNPCRequest:                        func() packet.Packet { return &packet.NPCRequest{} },
		IDPhotoTransfer:                     func() packet.Packet { return &packet.PhotoTransfer{} },
		IDModalFormRequest:                  func() packet.Packet { return &packet.ModalFormRequest{} },
		IDModalFormResponse:                 func() packet.Packet { return &packet.ModalFormResponse{} },
		IDServerSettingsRequest:             func() packet.Packet { return &packet.ServerSettingsRequest{} },
		IDServerSettingsResponse:            func() packet.Packet { return &packet.ServerSettingsResponse{} },
		IDShowProfile:                       func() packet.Packet { return &packet.ShowProfile{} },
		IDSetDefaultGameType:                func() packet.Packet { return &packet.SetDefaultGameType{} },
		IDRemoveObjective:                   func() packet.Packet { return &packet.RemoveObjective{} },
		IDSetDisplayObjective:               func() packet.Packet { return &packet.SetDisplayObjective{} },
		IDSetScore:                          func() packet.Packet { return &SetScore{} },
		IDLabTable:                          func() packet.Packet { return &packet.LabTable{} },
		IDUpdateBlockSynced:                 func() packet.Packet { return &UpdateBlockSynced{} },
		IDMoveActorDelta:                    func() packet.Packet { return &MoveActorDelta{} },
		IDSetScoreboardIdentity:             func() packet.Packet { return &packet.SetScoreboardIdentity{} },
		IDSetLocalPlayerAsInitialised:       func() packet.Packet { return &packet.SetLocalPlayerAsInitialised{} },
		IDUpdateSoftEnum:                    func() packet.Packet { return &packet.UpdateSoftEnum{} },
		IDNetworkStackLatency:               func() packet.Packet { return &packet.NetworkStackLatency{} },
		IDScriptCustomEvent:                 func() packet.Packet { return &packet.ScriptCustomEvent{} },
		IDSpawnParticleEffect:               func() packet.Packet { return &packet.SpawnParticleEffect{} },
		IDAvailableActorIdentifiers:         func() packet.Packet { return &packet.AvailableActorIdentifiers{} },
		IDNetworkChunkPublisherUpdate:       func() packet.Packet { return &packet.NetworkChunkPublisherUpdate{} },
		IDBiomeDefinitionList:               func() packet.Packet { return &BiomeDefinitionList{} },
		IDLevelSoundEvent:                   func() packet.Packet { return &LevelSoundEvent{} },
		IDLevelEventGeneric:                 func() packet.Packet { return &packet.LevelEventGeneric{} },
		IDLecternUpdate:                     func() packet.Packet { return &LecternUpdate{} },
		IDClientCacheStatus:                 func() packet.Packet { return &packet.ClientCacheStatus{} },
		IDOnScreenTextureAnimation:          func() packet.Packet { return &OnScreenTextureAnimation{} },
		IDMapCreateLockedCopy:               func() packet.Packet { return &packet.MapCreateLockedCopy{} },
		IDStructureTemplateDataRequest:      func() packet.Packet { return &StructureTemplateDataRequest{} },
		IDStructureTemplateDataResponse:     func() packet.Packet { return &packet.StructureTemplateDataResponse{} },
		IDClientCacheBlobStatus:             func() packet.Packet { return &ClientCacheBlobStatus{} },
		IDClientCacheMissResponse:           func() packet.Packet { return &packet.ClientCacheMissResponse{} },
		IDEducationSettings:                 func() packet.Packet { return &packet.EducationSettings{} },
		IDEmote:                             func() packet.Packet { return &packet.Emote{} },
		IDMultiPlayerSettings:               func() packet.Packet { return &packet.MultiPlayerSettings{} },
		IDSettingsCommand:                   func() packet.Packet { return &packet.SettingsCommand{} },
		IDAnvilDamage:                       func() packet.Packet { return &AnvilDamage{} },
		IDCompletedUsingItem:                func() packet.Packet { return &packet.CompletedUsingItem{} },
		IDNetworkSettings:                   func() packet.Packet { return &packet.NetworkSettings{} },
		IDPlayerAuthInput:                   func() packet.Packet { return &PlayerAuthInput{} },
		IDCreativeContent:                   func() packet.Packet { return &CreativeContent{} },
		IDPlayerEnchantOptions:              func() packet.Packet { return &packet.PlayerEnchantOptions{} },
		IDItemStackRequest:                  func() packet.Packet { return &ItemStackRequest{} },
		IDItemStackResponse:                 func() packet.Packet { return &ItemStackResponse{} },
		IDPlayerArmourDamage:                func() packet.Packet { return &PlayerArmourDamage{} },
		IDCodeBuilder:                       func() packet.Packet { return &packet.CodeBuilder{} },
		IDUpdatePlayerGameType:              func() packet.Packet { return &UpdatePlayerGameType{} },
		IDEmoteList:                         func() packet.Packet { return &packet.EmoteList{} },
		IDPositionTrackingDBServerBroadcast: func() packet.Packet { return &packet.PositionTrackingDBServerBroadcast{} },
		IDPositionTrackingDBClientRequest:   func() packet.Packet { return &packet.PositionTrackingDBClientRequest{} },
		IDDebugInfo:                         func() packet.Packet { return &packet.DebugInfo{} },
		IDPacketViolationWarning:            func() packet.Packet { return &packet.PacketViolationWarning{} },
		IDMotionPredictionHints:             func() packet.Packet { return &packet.MotionPredictionHints{} },
		IDAnimateEntity:                     func() packet.Packet { return &packet.AnimateEntity{} },
		IDCameraShake:                       func() packet.Packet { return &packet.CameraShake{} },
		IDPlayerFog:                         func() packet.Packet { return &packet.PlayerFog{} },
		IDCorrectPlayerMovePrediction:       func() packet.Packet { return &CorrectPlayerMovePrediction{} },
		IDItemRegistry:                      func() packet.Packet { return &packet.ItemRegistry{} },
		IDFilterText:                        func() packet.Packet { return &packet.FilterText{} },
		IDClientBoundDebugRenderer:          func() packet.Packet { return &packet.ClientBoundDebugRenderer{} },
		IDSyncActorProperty:                 func() packet.Packet { return &packet.SyncActorProperty{} },
		IDAddVolumeEntity:                   func() packet.Packet { return &AddVolumeEntity{} },
		IDRemoveVolumeEntity:                func() packet.Packet { return &RemoveVolumeEntity{} },
		IDSimulationType:                    func() packet.Packet { return &packet.SimulationType{} },
		IDNPCDialogue:                       func() packet.Packet { return &packet.NPCDialogue{} },
		IDEducationResourceURI:              func() packet.Packet { return &packet.EducationResourceURI{} },
		IDCreatePhoto:                       func() packet.Packet { return &packet.CreatePhoto{} },
		IDUpdateSubChunkBlocks:              func() packet.Packet { return &UpdateSubChunkBlocks{} },
		IDPhotoInfoRequest:                  func() packet.Packet { return &packet.PhotoInfoRequest{} },
		IDSubChunk:                          func() packet.Packet { return &SubChunk{} },
		IDSubChunkRequest:                   func() packet.Packet { return &SubChunkRequest{} },
		IDClientStartItemCooldown:           func() packet.Packet { return &packet.ClientStartItemCooldown{} },
		IDScriptMessage:                     func() packet.Packet { return &packet.ScriptMessage{} },
		IDCodeBuilderSource:                 func() packet.Packet { return &packet.CodeBuilderSource{} },
		IDTickingAreasLoadStatus:            func() packet.Packet { return &packet.TickingAreasLoadStatus{} },
		IDDimensionData:                     func() packet.Packet { return &packet.DimensionData{} },
		IDAgentAction:                       func() packet.Packet { return &packet.AgentAction{} },
		IDChangeMobProperty:                 func() packet.Packet { return &ChangeMobProperty{} },
		IDLessonProgress:                    func() packet.Packet { return &LessonProgress{} },
		IDRequestAbility:                    func() packet.Packet { return &packet.RequestAbility{} },
		IDRequestPermissions:                func() packet.Packet { return &RequestPermissions{} },
		IDToastRequest:                      func() packet.Packet { return &packet.ToastRequest{} },
		IDUpdateAbilities:                   func() packet.Packet { return &packet.UpdateAbilities{} },
		IDUpdateAdventureSettings:           func() packet.Packet { return &packet.UpdateAdventureSettings{} },
		IDDeathInfo:                         func() packet.Packet { return &packet.DeathInfo{} },
		IDEditorNetwork:                     func() packet.Packet { return &packet.EditorNetwork{} },
		IDFeatureRegistry:                   func() packet.Packet { return &packet.FeatureRegistry{} },
		IDServerStats:                       func() packet.Packet { return &packet.ServerStats{} },
		IDRequestNetworkSettings:            func() packet.Packet { return &packet.RequestNetworkSettings{} },
		IDGameTestRequest:                   func() packet.Packet { return &packet.GameTestRequest{} },
		IDGameTestResults:                   func() packet.Packet { return &packet.GameTestResults{} },
		IDUpdateClientInputLocks:            func() packet.Packet { return &UpdateClientInputLocks{} },
		IDClientCheatAbility:                func() packet.Packet { return &packet.ClientCheatAbility{} },
		IDCameraPresets:                     func() packet.Packet { return &packet.CameraPresets{} },
		IDUnlockedRecipes:                   func() packet.Packet { return &packet.UnlockedRecipes{} },
		IDCameraInstruction:                 func() packet.Packet { return &CameraInstruction{} },
		IDCompressedBiomeDefinitionList:     func() packet.Packet { return &CompressedBiomeDefinitionList{} },
		IDTrimData:                          func() packet.Packet { return &packet.TrimData{} },
		IDOpenSign:                          func() packet.Packet { return &OpenSign{} },
		IDAgentAnimation:                    func() packet.Packet { return &packet.AgentAnimation{} },
		IDRefreshEntitlements:               func() packet.Packet { return &packet.RefreshEntitlements{} },
		IDPlayerToggleCrafterSlotRequest:    func() packet.Packet { return &packet.PlayerToggleCrafterSlotRequest{} },
		IDSetPlayerInventoryOptions:         func() packet.Packet { return &SetPlayerInventoryOptions{} },
		IDSetHud:                            func() packet.Packet { return &packet.SetHud{} },
		IDAwardAchievement:                  func() packet.Packet { return &packet.AwardAchievement{} },
		IDClientBoundCloseForm:              func() packet.Packet { return &packet.ClientBoundCloseForm{} },
		IDServerBoundLoadingScreen:          func() packet.Packet { return &packet.ServerBoundLoadingScreen{} },
		IDJigsawStructureData:               func() packet.Packet { return &JigsawStructureData{} },
		IDCurrentStructureFeature:           func() packet.Packet { return &packet.CurrentStructureFeature{} },
		IDServerBoundDiagnostics:            func() packet.Packet { return &ServerBoundDiagnostics{} },
		IDCameraAimAssist:                   func() packet.Packet { return &CameraAimAssist{} },
		IDContainerRegistryCleanup:          func() packet.Packet { return &packet.ContainerRegistryCleanup{} },
		IDMovementEffect:                    func() packet.Packet { return &packet.MovementEffect{} },
		IDSetMovementAuthority:              func() packet.Packet { return &SetMovementAuthority{} },
		IDCameraAimAssistPresets:            func() packet.Packet { return &CameraAimAssistPresets{} },
		IDClientCameraAimAssist:             func() packet.Packet { return &packet.ClientCameraAimAssist{} },
		IDClientMovementPredictionSync:      func() packet.Packet { return &ClientMovementPredictionSync{} },
		IDUpdateClientOptions:               func() packet.Packet { return &UpdateClientOptions{} },
		IDPlayerVideoCapture:                func() packet.Packet { return &packet.PlayerVideoCapture{} },
		IDPlayerUpdateEntityOverrides:       func() packet.Packet { return &PlayerUpdateEntityOverrides{} },
	}
	p := packet.Pool{}
	for id, pk := range serverOriginating {
		p[id] = pk
	}
	return p
}

func NewClientPool() packet.Pool {
	clientOriginating := map[uint32]func() packet.Packet{
		IDLogin:                           func() packet.Packet { return &packet.Login{} },
		IDClientToServerHandshake:         func() packet.Packet { return &packet.ClientToServerHandshake{} },
		IDResourcePackClientResponse:      func() packet.Packet { return &ResourcePackClientResponse{} },
		IDText:                            func() packet.Packet { return &Text{} },
		IDMovePlayer:                      func() packet.Packet { return &MovePlayer{} },
		IDPassengerJump:                   func() packet.Packet { return &PassengerJump{} },
		IDTickSync:                        func() packet.Packet { return &TickSync{} },
		IDActorEvent:                      func() packet.Packet { return &ActorEvent{} },
		IDInventoryTransaction:            func() packet.Packet { return &InventoryTransaction{} },
		IDMobEquipment:                    func() packet.Packet { return &packet.MobEquipment{} },
		IDInteract:                        func() packet.Packet { return &Interact{} },
		IDBlockPickRequest:                func() packet.Packet { return &packet.BlockPickRequest{} },
		IDActorPickRequest:                func() packet.Packet { return &packet.ActorPickRequest{} },
		IDPlayerAction:                    func() packet.Packet { return &PlayerAction{} },
		IDSetActorLink:                    func() packet.Packet { return &packet.SetActorLink{} },
		IDAnimate:                         func() packet.Packet { return &Animate{} },
		IDRespawn:                         func() packet.Packet { return &packet.Respawn{} },
		IDContainerOpen:                   func() packet.Packet { return &ContainerOpen{} },
		IDContainerClose:                  func() packet.Packet { return &ContainerClose{} },
		IDAdventureSettings:               func() packet.Packet { return &packet.AdventureSettings{} },
		IDPlayerInput:                     func() packet.Packet { return &PlayerInput{} },
		IDSetPlayerGameType:               func() packet.Packet { return &packet.SetPlayerGameType{} },
		IDMapInfoRequest:                  func() packet.Packet { return &packet.MapInfoRequest{} },
		IDRequestChunkRadius:              func() packet.Packet { return &RequestChunkRadius{} },
		IDBossEvent:                       func() packet.Packet { return &BossEvent{} },
		IDShowCredits:                     func() packet.Packet { return &packet.ShowCredits{} },
		IDCommandRequest:                  func() packet.Packet { return &CommandRequest{} },
		IDCommandBlockUpdate:              func() packet.Packet { return &CommandBlockUpdate{} },
		IDResourcePackChunkRequest:        func() packet.Packet { return &ResourcePackChunkRequest{} },
		IDStructureBlockUpdate:            func() packet.Packet { return &StructureBlockUpdate{} },
		IDPurchaseReceipt:                 func() packet.Packet { return &packet.PurchaseReceipt{} },
		IDPlayerSkin:                      func() packet.Packet { return &PlayerSkin{} },
		IDSubClientLogin:                  func() packet.Packet { return &packet.SubClientLogin{} },
		IDAutomationClientConnect:         func() packet.Packet { return &packet.AutomationClientConnect{} },
		IDBookEdit:                        func() packet.Packet { return &BookEdit{} },
		IDNPCRequest:                      func() packet.Packet { return &packet.NPCRequest{} },
		IDModalFormResponse:               func() packet.Packet { return &packet.ModalFormResponse{} },
		IDServerSettingsRequest:           func() packet.Packet { return &packet.ServerSettingsRequest{} },
		IDSetDefaultGameType:              func() packet.Packet { return &packet.SetDefaultGameType{} },
		IDLabTable:                        func() packet.Packet { return &packet.LabTable{} },
		IDSetLocalPlayerAsInitialised:     func() packet.Packet { return &packet.SetLocalPlayerAsInitialised{} },
		IDNetworkStackLatency:             func() packet.Packet { return &packet.NetworkStackLatency{} },
		IDScriptCustomEvent:               func() packet.Packet { return &packet.ScriptCustomEvent{} },
		IDLevelSoundEvent:                 func() packet.Packet { return &LevelSoundEvent{} },
		IDLecternUpdate:                   func() packet.Packet { return &LecternUpdate{} },
		IDClientCacheStatus:               func() packet.Packet { return &packet.ClientCacheStatus{} },
		IDMapCreateLockedCopy:             func() packet.Packet { return &packet.MapCreateLockedCopy{} },
		IDStructureTemplateDataRequest:    func() packet.Packet { return &StructureTemplateDataRequest{} },
		IDStructureTemplateDataResponse:   func() packet.Packet { return &packet.StructureTemplateDataResponse{} },
		IDClientCacheBlobStatus:           func() packet.Packet { return &ClientCacheBlobStatus{} },
		IDEmote:                           func() packet.Packet { return &packet.Emote{} },
		IDMultiPlayerSettings:             func() packet.Packet { return &packet.MultiPlayerSettings{} },
		IDSettingsCommand:                 func() packet.Packet { return &packet.SettingsCommand{} },
		IDAnvilDamage:                     func() packet.Packet { return &AnvilDamage{} },
		IDPlayerAuthInput:                 func() packet.Packet { return &PlayerAuthInput{} },
		IDItemStackRequest:                func() packet.Packet { return &ItemStackRequest{} },
		IDUpdatePlayerGameType:            func() packet.Packet { return &UpdatePlayerGameType{} },
		IDEmoteList:                       func() packet.Packet { return &packet.EmoteList{} },
		IDPositionTrackingDBClientRequest: func() packet.Packet { return &packet.PositionTrackingDBClientRequest{} },
		IDDebugInfo:                       func() packet.Packet { return &packet.DebugInfo{} },
		IDPacketViolationWarning:          func() packet.Packet { return &packet.PacketViolationWarning{} },
		IDFilterText:                      func() packet.Packet { return &packet.FilterText{} },
		IDCreatePhoto:                     func() packet.Packet { return &packet.CreatePhoto{} },
		IDPhotoInfoRequest:                func() packet.Packet { return &packet.PhotoInfoRequest{} },
		IDSubChunkRequest:                 func() packet.Packet { return &SubChunkRequest{} },
		IDScriptMessage:                   func() packet.Packet { return &packet.ScriptMessage{} },
		IDCodeBuilderSource:               func() packet.Packet { return &packet.CodeBuilderSource{} },
		IDRequestAbility:                  func() packet.Packet { return &packet.RequestAbility{} },
		IDRequestPermissions:              func() packet.Packet { return &RequestPermissions{} },
		IDEditorNetwork:                   func() packet.Packet { return &packet.EditorNetwork{} },
		IDRequestNetworkSettings:          func() packet.Packet { return &packet.RequestNetworkSettings{} },
		IDGameTestResults:                 func() packet.Packet { return &packet.GameTestResults{} },
		IDOpenSign:                        func() packet.Packet { return &OpenSign{} },
		IDBlockActorData:                  func() packet.Packet { return &BlockActorData{} },
		IDPlayerToggleCrafterSlotRequest:  func() packet.Packet { return &packet.PlayerToggleCrafterSlotRequest{} },
		IDSetPlayerInventoryOptions:       func() packet.Packet { return &SetPlayerInventoryOptions{} },
		IDServerBoundLoadingScreen:        func() packet.Packet { return &packet.ServerBoundLoadingScreen{} },
		IDServerBoundDiagnostics:          func() packet.Packet { return &ServerBoundDiagnostics{} },
		IDClientMovementPredictionSync:    func() packet.Packet { return &ClientMovementPredictionSync{} },
		IDUpdateClientOptions:             func() packet.Packet { return &UpdateClientOptions{} },
	}
	p := packet.Pool{}
	for id, pk := range clientOriginating {
		p[id] = pk
	}
	return p
}
